# .github/workflows/main.yml
name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: [actions/checkout@v4](https://github.com)
      
      - name: Run a one-line script
        run: echo Hello, world!
